name: todo_app
description: Graphql with flutter project

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  dartz: ^0.10.1
  json_annotation: ^4.5.0
  graphql: ^5.1.2-beta.1
  universal_platform:
    ^0.1.3
    # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

flutter:
  uses-material-design: true